name: Roguecraft
version: '0.1.0'
main: com.eldor.roguecraft.RoguecraftPlugin
api-version: '1.21'
author: Eldor
description: Minecraft Roguelike Plugin inspired by Megabonk
load: POSTWORLD
softdepend: [ProtocolLib, PlaceholderAPI, WorldGuard, Vault]

commands:
  roguecraft:
    description: Open the run GUI or manage arenas
    usage: /<command> [start|stop|stats|gui]
    aliases: [rc, roguelike]

permissions:
  roguecraft.*:
    description: All Roguecraft permissions
    default: op
    children:
      roguecraft.play: true
      roguecraft.admin: true
  roguecraft.play:
    description: Allows players to play Roguecraft
    default: true
  roguecraft.admin:
    description: Allows admin commands
    default: op
    children:
      roguecraft.admin.reload: true
      roguecraft.admin.arena: true
      roguecraft.admin.setup: true
  roguecraft.admin.reload:
    description: Allows reloading configuration
    default: op
  roguecraft.admin.arena:
    description: Allows managing arenas
    default: op
  roguecraft.admin.setup:
    description: Allows setting up arena regions
    default: op



